### ISSUE TITLE
stereo .wav -> stereo mp3

### ISSUE THREAD

**Issue by pamelajean** [cavpp/audio_convert#2]
if .wav's have 2 channels then .mp3's should have 2 channels and bit rate should equal 320000 (not 160000)

**Comment by henryborchers** [comment]
Was this produced using this script or one of my one off scripts?

**Comment by pamelajean** [comment]
not sure. i'm looking at museum of performance and design files. did you fix this particular script so 2 channel wav's create 2 channel mp3's? if so i'll (re)install this version...

**Comment by dericed** [comment]
Is the `makemp3` dependency from this: https://github.com/dericed/mediamicroservices/blob/master/makemp3?

**Comment by henryborchers** [comment]
derice,

My script doesn't use your script. 
It just uses:
- Python for the logic, 
- OneSheet (my metadata parsing library that uses  ffprobe to scan the source),
- lame to encode the file. 

pamelajean,
I need to see the file that keeps failing on you because I have logic in my script that shouldn't allow this to happen.

**Comment by pamelajean** [comment]
ok will bring the drive over in a bit.

hi dave! [?]

p

On Tue, Jun 9, 2015 at 11:43 AM, henryborchers notifications@github.com
wrote:

> derice,
> 
> My script doesn't use your script.
> It just uses:
> - Python for the logic,
> - OneSheet (my metadata parsing library that uses ffprobe to scan the
>   source),
> - lame to encode the file.
> 
> pamelajean,
> I need to see the file that keeps failing on you because I have logic in
> my script that shouldn't allow this to happen.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cavpp/audio_convert/issues/2#issuecomment-110461095.

## 

 Pamela Jean Vadakan
California Light and Sound
http://s.wisestamp.com/links?url=http%3A%2F%2Farchive.org%2Fdetails%2Fcalifornialightandsound
Preservation Department
20 Doe Library
University of California, Berkeley
Berkeley, CA 94720
phone: 510.642.4665

**Comment by henryborchers** [comment]
Issue has been resolved without any changes to the code.
